Repository TechVisionn/tech-backend, pull requests merged in 2023-09, with the labels that each got.

#18 7: feat-initial config db and migration
  flaskr/__init__.py
  flaskr/app.py
  flaskr/config_app.py
  flaskr/db.py
  flaskr/migrate.py
  requirements.txt
Labels: back-end, database

#20 Feature 10
  flaskr/app.py
  flaskr/migrate.py
  flaskr/models/__init__.py
  flaskr/models/sicor_op_estado.py
Labels: back-end

#22 Feature 21
  flaskr/app.py
  flaskr/db.py
  flaskr/models/sicor_gleba.py
  flaskr/models/sicor_op_estado.py
  flaskr/resources/__init__.py
  flaskr/resources/gleba.py
  flaskr/routes.py
  requirements.txt
Labels: back-end

#24 fix: query gleba
  flaskr/models/sicor_gleba.py
  flaskr/resources/gleba.py
Labels: bug

#25 15: feat-setup back end
  README.md
Labels: documentation

#30 28: feat-create pdf with informations database
  flaskr/app.py
  flaskr/db.py
  flaskr/models/sicor_gleba.py
  flaskr/models/test_pdf.py
  flaskr/resources/gleba.py
  flaskr/services/gleba.py
  requirements.txt
Labels: back-end

#33 add cors in project
  flaskr/app.py
  requirements.txt
Labels: back-end

#35 Feature 34
  flaskr/models/glebas_sp.py
  flaskr/models/saida5.py
  flaskr/models/sicor_gleba.py
  flaskr/models/sicor_op_estado.py
  flaskr/models/test_pdf.py
Labels: back-end

#37 Feat: Relatório com as glebas
  flaskr/models/__init__.py
  flaskr/models/glebas_sp.py
  flaskr/models/saida5.py
  flaskr/resources/gleba.py
  flaskr/services/gleba.py
Labels: back-end
