Repository TechVisionn/tech-backend, pull requests merged in 2023-10, with the labels that each got.

#49 Config database using dao
  flaskr/db/__init__.py
  flaskr/db/config_app.py
  flaskr/db/dao/README.md
  flaskr/db/dao/__init__.py
  flaskr/db/dao/gleba.py
  flaskr/db/entity.py
  test.py
Labels: back-end, database, data

#50 41:feat-login
  flaskr/app.py
  flaskr/config_app.py
  flaskr/db.py
  flaskr/db/dao/gleba.py
  flaskr/db/entity.py
  flaskr/db/mongo_serve.py
  flaskr/resources/gleba.py
  flaskr/resources/user.py
  flaskr/routes.py
  flaskr/security.py
  flaskr/services/gleba.py
  requirements.txt
  test.py
Labels: back-end

#52 42:feat-config token in application
  flaskr/resources/gleba.py
  flaskr/resources/token.py
  flaskr/resources/user.py
  flaskr/routes.py
  flaskr/security.py
Labels: back-end

#55 39:feat-config terms
  flaskr/resources/token.py
  flaskr/resources/user.py
Labels: back-end, database

#57 56: Feat - land and terms of acceptance
  flaskr/db/dao/gleba.py
  flaskr/db/entity.py
  flaskr/resources/gleba.py
  flaskr/resources/token.py
  flaskr/resources/user.py
  flaskr/routes.py
  test.py
Labels: back-end, database

#58 51-doc step config database
  README.md
Labels: documentation

#60 dev:feat-return glebas in dict and login with token
  README.md
  flaskr/__init__.py
  flaskr/app.py
  flaskr/db/__init__.py
  flaskr/db/config_app.py
  flaskr/db/dao/README.md
  flaskr/db/dao/__init__.py
  flaskr/db/dao/gleba.py
  flaskr/db/entity.py
  flaskr/db/mongo_serve.py
  flaskr/resources/__init__.py
  flaskr/resources/gleba.py
  flaskr/resources/token.py
  flaskr/resources/user.py
  flaskr/routes.py
  flaskr/security.py
  flaskr/services/gleba.py
  requirements.txt
Labels: back-end, database

#61 feature-100
  flaskr/resources/gleba.py
  flaskr/resources/token.py
  flaskr/resources/user.py
Labels: back-end

#62 feat: terms
  flaskr/db/dao/gleba.py
  flaskr/resources/token.py
  flaskr/resources/user.py
Labels: back-end

#70 Feature 63
  flaskr/resources/terms.py
  flaskr/resources/token.py
  flaskr/routes.py
Labels: back-end

#71 feat: validation terms
  flaskr/resources/terms.py
  flaskr/resources/token.py
  flaskr/resources/user.py
Labels: back-end
